# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inci', '0002_auto_20170309_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=300, unique=True)),
                ('description', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='blog.Article')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=300, unique=True)),
                ('description', models.CharField(max_length=300, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='inci.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
