# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 02:29
from __future__ import unicode_literals

import blog.models.subscription
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_feedback_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='subscription',
            name='token',
            field=models.TextField(default=blog.models.subscription.generate_token),
        ),
    ]
