# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170430_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
