# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170511_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[- \\w]+$', "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[- \\w]+$', "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
