# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('year_of_creation', models.IntegerField(verbose_name='Year of creation (YYYY)')),
                ('country_of_creation', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='certifications/')),
            ],
            options={
                'ordering': ['certification_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inci_name', models.CharField(max_length=200, unique=True, verbose_name='INCI name')),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Additional information')),
                ('is_biodegradable', models.BooleanField(default=False, verbose_name='Biodegradable')),
                ('is_vegetable', models.BooleanField(default=False, verbose_name='Vegetable')),
                ('is_mineral', models.BooleanField(default=False, verbose_name='Mineral')),
                ('is_chemical', models.BooleanField(default=False, verbose_name='Chemical')),
                ('is_petrochemical', models.BooleanField(default=False, verbose_name='Petrochemical')),
                ('production_cost', models.IntegerField(choices=[(1, 'low'), (2, 'mid'), (3, 'high')], default=1)),
            ],
            options={
                'ordering': ['inci_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price_range', models.IntegerField(choices=[(1, 'low range'), (2, 'mid range'), (3, 'top range')], default=1)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inci.Brand')),
                ('categories', models.ManyToManyField(related_name='products', to='inci.Category')),
                ('certifications', models.ManyToManyField(blank=True, related_name='products', to='inci.Certification')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='inci.Ingredient')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='types',
            field=models.ManyToManyField(related_name='ingredients', to='inci.Type'),
        ),
    ]
