# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inci', '0002_auto_20170309_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certifications',
            field=models.ManyToManyField(related_name='products', to='inci.Certification'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', to='inci.Ingredient'),
        ),
    ]
